#!/bin/sh

FILENAME=~/.demon

if [ -z $1 ]; then
	VOICE=Whisper
else
	VOICE=$1
fi


touch $FILENAME

cat /usr/share/dict/words | rev | gshuf > $FILENAME

cat $FILENAME | say -v $VOICE &

#cat $FILENAME | style --random | xargs printf
#rm $FILENAME
