#!/bin/sh

#array=(`cat /usr/share/dict/words | rev | gshuf`);
#for i in "${array[@]}"; do
#	say -r 0.25 -v Whisper $i;
#done

VOICE="Whisper"

SUGGESTED_VOICE="$1"
if [ -z ${SUGGESTED_VOICE+x} ]; then VOICE="$1"; fi;

cat /usr/share/dict/words | rev | gshuf | say -r 0.25 -v $VOICE
