#!/bin/sh
# http://misc.flogisoft.com/bash/tip_colors_and_formatting

#################
# Formatting
#################

function bold () {
	echo "\033[1m$1";
}

function dim () {
	echo "\033[2m$1";
}

function underline () {
	echo "\033[4m$1";
}

function blink () {
	echo "\033[5m$1";
}

function reverse () {
	echo "\033[7m$1";
}

function hidden () {
	echo "\033[8m$1";
}

#################
# Color
#################

function default () {
	echo "\033[39m$1";
}

function black () {
	echo "\033[30m$1";
}

function red () {
	echo "\033[31m$1";
}

function green () {
	echo "\033[32m$1";
}

function yellow () {
	echo "\033[33m$1";
}

function blue () {
	echo "\033[34m$1";
}

function magenta () {
	echo "\033[35m$1";
}

function cyan () {
	echo "\033[36m$1";
}

function lGray () {
	echo "\033[37m$1";
}

function dGray () {
	echo "\033[90m$1";
}

function lRed () {
	echo "\033[91m$1";
}

function lGreen () {
	echo "\033[92m$1";
}

function lYellow () {
	echo "\033[93m$1";
}

function lBlue () {
	echo "\033[94m$1";
}

function lMagenta () {
	echo "\033[95m$1";
}

function lCyan () {
	echo "\033[96m$1";
}

function white () {
	echo "\033[97m$1";
}

#################
# Highlighting
#################

function _default () {
	echo "\033[49m$1";
}

function _black () {
	echo "\033[40m$1";
}

function _red () {
	echo "\033[41m$1";
}

function _green () {
	echo "\033[42m$1";
}

function _yellow () {
	echo "\033[43m$1";
}

function _blue () {
	echo "\033[44$1";
}

function _magenta () {
	echo "\033[45$1";
}

function _cyan () {
	echo "\033[46$1";
}

function _lGray () {
	echo "\033[47$1";
}

function _dGray () {
	echo "\033[100$1";
}

function _lRed () {
	echo "\033[101$1";
}

function _lGreen () {
	echo "\033[102$1";
}

function _lYellow () {
	echo "\033[103$1";
}

function _lBlue () {
	echo "\033[104$1";
}

function _lMagenta () {
	echo "\033[105$1";
}

function _lCyan () {
	echo "\033[106$1";
}

function _white () {
	echo "\033[107$1";
}


function randomValue () {
	local array=($@);
	local i=$RANDOM;
	i=$((i%${#array[@]}));

	echo "${array[$i]}";
}


formatNames=(bold dim underline blink reverse hidden);
colorNames=(default black red green yellow blue magenta cyan lGray dGray); # lRed lGreen lYellow lBlue lMagenta lCyan white);
highlightNames=(_default _black _red _green _yellow _blue _magenta _cyan _lGray _dGray); # _lRed _lGreen _lYellow _lBlue _lMagenta _lCyan _white);


styleValues=($1);
message="$2";

if [ "$1" = "--random" ]; then
	styleValues=();
	styleValues[0]=`randomValue "${formatNames[@]}"`;
	styleValues[1]=`randomValue "${colorNames[@]}"`;
	styleValues[2]=`randomValue "${highlightNames[@]}"`;
fi

for style in "${styleValues[@]}"; do
	message=`$style "$message"`;
done

echo "$message\033[0m";
